// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu6Tddwcgqz-zGyJ7XEqKz8riis6Vk5ws',
    appId: '1:1020839545726:web:4de6c878aae7523aaf812f',
    messagingSenderId: '1020839545726',
    projectId: 'life-pilot-2025',
    authDomain: 'life-pilot-2025.firebaseapp.com',
    storageBucket: 'life-pilot-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2lhUWjKYAu_P06mMAYanUNo8AhDGUHNY',
    appId: '1:1020839545726:android:16e1379450d0c067af812f',
    messagingSenderId: '1020839545726',
    projectId: 'life-pilot-2025',
    storageBucket: 'life-pilot-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNVR7DMhSx3HnCuDpBGaUFiad5m7FRpM',
    appId: '1:1020839545726:ios:75f6a9cde87e38fcaf812f',
    messagingSenderId: '1020839545726',
    projectId: 'life-pilot-2025',
    storageBucket: 'life-pilot-2025.firebasestorage.app',
    iosBundleId: 'com.example.lifePilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNVR7DMhSx3HnCuDpBGaUFiad5m7FRpM',
    appId: '1:1020839545726:ios:75f6a9cde87e38fcaf812f',
    messagingSenderId: '1020839545726',
    projectId: 'life-pilot-2025',
    storageBucket: 'life-pilot-2025.firebasestorage.app',
    iosBundleId: 'com.example.lifePilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu6Tddwcgqz-zGyJ7XEqKz8riis6Vk5ws',
    appId: '1:1020839545726:web:1a57b5732a916080af812f',
    messagingSenderId: '1020839545726',
    projectId: 'life-pilot-2025',
    authDomain: 'life-pilot-2025.firebaseapp.com',
    storageBucket: 'life-pilot-2025.firebasestorage.app',
  );
}
