import 'package:flutter/widgets.dart';
import 'package:life_pilot/l10n/app_localizations.dart';

class EventCountry {
  final String code;

  const EventCountry(this.code);

  String label(BuildContext context) {
    final loc = AppLocalizations.of(context)!;
    return switch (code) {
      'TW' => loc.countryTaiwan,
      'JP' => loc.countryJapan,
      'KR' => loc.countrySouthKorea,
      'SG' => loc.countrySingapore,
      'US' => loc.countryUnitedStates,
      'CA' => loc.countryCanada,
      'CN' => loc.countryChina,
      'HK' => loc.countryHongKong,
      'MO' => loc.countryMacau,
      'TH' => loc.countryThailand,
      'VN' => loc.countryVietnam,
      'MY' => loc.countryMalaysia,
      'ID' => loc.countryIndonesia,
      'PH' => loc.countryPhilippines,
      'AU' => loc.countryAustralia,
      'NZ' => loc.countryNewZealand,
      'GB' => loc.countryUnitedKingdom,
      'FR' => loc.countryFrance,
      'DE' => loc.countryGermany,
      'IT' => loc.countryItaly,
      'ES' => loc.countrySpain,
      'NL' => loc.countryNetherlands,
      'CH' => loc.countrySwitzerland,
      'IN' => loc.countryIndia,
      'AE' => loc.countryUnitedArabEmirates,
      _ => code,
    };
  }

  static const values = <EventCountry>[
    EventCountry('TW'),
    EventCountry('JP'),
    EventCountry('KR'),
    EventCountry('SG'),
    EventCountry('US'),
    EventCountry('CA'),
    EventCountry('CN'),
    EventCountry('HK'),
    EventCountry('MO'),
    EventCountry('TH'),
    EventCountry('VN'),
    EventCountry('MY'),
    EventCountry('ID'),
    EventCountry('PH'),
    EventCountry('AU'),
    EventCountry('NZ'),
    EventCountry('GB'),
    EventCountry('FR'),
    EventCountry('DE'),
    EventCountry('IT'),
    EventCountry('ES'),
    EventCountry('NL'),
    EventCountry('CH'),
    EventCountry('IN'),
    EventCountry('AE'),
  ];

  static String normalize(String? value) {
    final normalized = value?.trim() ?? '';
    if (normalized.isEmpty || normalized.toLowerCase() == 'taiwan') return 'TW';
    final upper = normalized.toUpperCase();
    if (values.any((country) => country.code == upper)) return upper;
    const aliases = <String, String>{
      'taiwan': 'TW',
      '台灣': 'TW',
      '臺灣': 'TW',
      '台湾': 'TW',
      '대만': 'TW',
      'japan': 'JP',
      '日本': 'JP',
      '일본': 'JP',
      'south korea': 'KR',
      'korea': 'KR',
      '韓國': 'KR',
      '韓国': 'KR',
      '대한민국': 'KR',
      'singapore': 'SG',
      '新加坡': 'SG',
      'シンガポール': 'SG',
      '싱가포르': 'SG',
      'united states': 'US',
      'usa': 'US',
      '美國': 'US',
      '美国': 'US',
      'アメリカ': 'US',
      '미국': 'US',
      'canada': 'CA',
      '加拿大': 'CA',
      'カナダ': 'CA',
      '캐나다': 'CA',
      'china': 'CN',
      '中國': 'CN',
      '中国': 'CN',
      '중국': 'CN',
      'hong kong': 'HK',
      '香港': 'HK',
      '홍콩': 'HK',
      'macau': 'MO',
      '澳門': 'MO',
      '澳门': 'MO',
      'マカオ': 'MO',
      '마카오': 'MO',
      'thailand': 'TH',
      '泰國': 'TH',
      '泰国': 'TH',
      'タイ': 'TH',
      '태국': 'TH',
      'vietnam': 'VN',
      '越南': 'VN',
      'ベトナム': 'VN',
      '베트남': 'VN',
      'malaysia': 'MY',
      '馬來西亞': 'MY',
      '马来西亚': 'MY',
      'マレーシア': 'MY',
      '말레이시아': 'MY',
      'indonesia': 'ID',
      '印尼': 'ID',
      'インドネシア': 'ID',
      '인도네시아': 'ID',
      'philippines': 'PH',
      '菲律賓': 'PH',
      '菲律宾': 'PH',
      'フィリピン': 'PH',
      '필리핀': 'PH',
      'australia': 'AU',
      '澳洲': 'AU',
      'オーストラリア': 'AU',
      '호주': 'AU',
      'new zealand': 'NZ',
      '紐西蘭': 'NZ',
      '新西兰': 'NZ',
      'ニュージーランド': 'NZ',
      '뉴질랜드': 'NZ',
      'united kingdom': 'GB',
      'uk': 'GB',
      '英國': 'GB',
      '英国': 'GB',
      'イギリス': 'GB',
      '영국': 'GB',
      'france': 'FR',
      '法國': 'FR',
      '法国': 'FR',
      'フランス': 'FR',
      '프랑스': 'FR',
      'germany': 'DE',
      '德國': 'DE',
      '德国': 'DE',
      'ドイツ': 'DE',
      '독일': 'DE',
      'italy': 'IT',
      '義大利': 'IT',
      '意大利': 'IT',
      'イタリア': 'IT',
      '이탈리아': 'IT',
      'spain': 'ES',
      '西班牙': 'ES',
      'スペイン': 'ES',
      '스페인': 'ES',
      'netherlands': 'NL',
      '荷蘭': 'NL',
      '荷兰': 'NL',
      'オランダ': 'NL',
      '네덜란드': 'NL',
      'switzerland': 'CH',
      '瑞士': 'CH',
      'スイス': 'CH',
      '스위스': 'CH',
      'india': 'IN',
      '印度': 'IN',
      'インド': 'IN',
      '인도': 'IN',
      'united arab emirates': 'AE',
      'uae': 'AE',
      '阿拉伯聯合大公國': 'AE',
      '阿拉伯联合酋长国': 'AE',
      'アラブ首長国連邦': 'AE',
      '아랍에미리트': 'AE',
    };
    final alias = aliases[normalized.toLowerCase()];
    if (alias != null) return alias;
    return 'TW';
  }
}
